{
 "title": "Climate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Main Floor Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{domain=\"sensor\",entity=\"sensor.main_floor_temperature\"}"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature{forecast=\"*\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity!~\".*pixel.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}