{
 "title": "House Climate",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "AC Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(homeassistant_climate_action{action=\"cooling\"}[$__range])) * $__range_s)"
    }
   ]
  },
  {
   "title": "Heating Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(homeassistant_climate_action{action=\"heating\"}[$__range])) * $__range_s)"
    }
   ]
  },
  {
   "title": "Average Indoor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "homeassistant_climate_current_temperature_celsius"
    }
   ]
  },
  {
   "title": "Average Outdoor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((avg_over_time(weather_temperature{forecast=\"*\"}[$__range])  - 32) * (5/9))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "homeassistant_climate_current_temperature_celsius",
     "legendFormat": "Indoor"
    },
    {
     "expr": "(weather_temperature{forecast=\"*\"} - 32) * (5/9)",
     "legendFormat": "Outdoor"
    }
   ]
  },
  {
   "title": "Thermostat Setting",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "homeassistant_climate_action", "legendFormat": "{{action}}" }
   ]
  }
 ]
}