{
 "title": "Media Dashboard",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SABnzbd - ${sabnzdb_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sabnzdb_instance" },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(sabnzbd_downloaded_bytes)", "legendFormat": "Lifetime" },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes{instance=\"${sabnzdb_instance}\"}[$__range]))",
     "legendFormat": "Recent"
    },
    {
     "expr": "sabnzbd_queue_length{instance=\"${sabnzdb_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sabnzbd_total_bytes{instance=\"${sabnzdb_instance}\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "sabnzbd_remaining_bytes{instance=\"${sabnzdb_instance}\"}",
     "legendFormat": "Remaining"
    },
    {
     "expr": "sum(sabnzbd_server_articles_success{instance=\"${sabnzdb_instance}\"}) / sum(sabnzbd_server_articles_total{instance=\"${sabnzdb_instance}\"})",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_quota_bytes", "legendFormat": "Size" },
    {
     "expr": "1 - max(sabnzbd_remaining_quota_bytes{instance=\"${sabnzdb_instance}\"} / sabnzbd_quota_bytes{instance=\"${sabnzdb_instance}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sabnzbd_remaining_quota_bytes{instance=\"${sabnzdb_instance}\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_article_cache_articles", "legendFormat": "Articles" },
    {
     "expr": "sabnzbd_article_cache_bytes{instance=\"${sabnzdb_instance}\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sabnzbd\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sabnzbd\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_status", "legendFormat": "Mode" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_time_estimate_seconds", "legendFormat": "Time Remaining" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_speed_bps", "legendFormat": "D/L Speed" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_paused_all", "legendFormat": "Hard Pause" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_pause_duration_seconds", "legendFormat": "Resume In" }
   ]
  },
  {
   "title": "Disk Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sabnzbd_disk_used_bytes / sabnzbd_disk_total_bytes{folder=\"download\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "min(sabnzbd_disk_used_bytes{instance=\"${sabnzdb_instance}\",folder=\"complete\"} / sabnzbd_disk_total_bytes{instance=\"${sabnzdb_instance}\",folder=\"complete\"})",
     "legendFormat": "Complete"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Lifetime Downloads By Server",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_downloaded_bytes",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Downloaded By Server",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Download Percent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "radarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_wanted_total", "legendFormat": "Wanted" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_queue_total", "legendFormat": "Queued" },
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_history_total", "legendFormat": "History" },
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Disk Used" },
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "targets": [
    { "expr": "radarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sonarr - ${sonarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }, "repeat": "sonarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_system_status", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_queue_total", "legendFormat": "Queued" },
    { "expr": "sonarr_history_total", "legendFormat": "History" },
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total)",
     "legendFormat": "Series Monitored"
    },
    { "expr": "max(sonarr_series_total)", "legendFormat": "Series Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total)",
     "legendFormat": "Episodes Missing"
    },
    { "expr": "max(sonarr_episode_total)", "legendFormat": "Episodes Total" }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "targets": [
    { "expr": "sonarr_system_health_issues", "legendFormat": "__auto" }
   ]
  }
 ]
}