{
 "title": "UPS",
 "description": "Displays monitoring data collected from APC uninterruptible power supplies via SNMP.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_info" }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "Time spent on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "UPS load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Estimated uptime on batteries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Charge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "Time On",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "AC and load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Output load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  }
 ]
}